import job_logo from "../../my-app/src/assets/job_logo.webp";
import job_logo_2 from "../../my-app/src/assets/job_logo_2.webp"
const MyData = [
  {
    id:1,
    time: "10 min ago",
    img: job_logo,
    job_type: "Forward Security Director",
    job_desc: "Bauch, Schuppe and Schulist Co",
    about_detail: "Hotels & Tourism",
    type: "full time",
    salary: "$40000-$42000",
    area: "New-York, USA",
  },
   {
    id:2,
    time: "12 min ago",
    img: job_logo_2,
    job_type: "Regional Creative Facilitator",
    job_desc: "Wisozk - Becker Co",
    about_detail: "Media",
    type: "full time",
    salary: "$$28000-$32000",
    area: "Los- Angeles, USA",
  },
  {
    id:3,
    time: "10 min ago",
    img: job_logo,
    job_type: "Forward Security Director",
    job_desc: "Bauch, Schuppe and Schulist Co",
    about_detail: "Hotels & Tourism",
    type: "full time",
    salary: "$40000-$42000",
    area: "New-York, USA",
  },
   {
    id:4,
    time: "12 min ago",
    img: job_logo_2,
    job_type: "Regional Creative Facilitator",
    job_desc: "Wisozk - Becker Co",
    about_detail: "Media",
    type: "full time",
    salary: "$$28000-$32000",
    area: "Los- Angeles, USA",
  },
  {
    id:5,
    time: "10 min ago",
    img: job_logo,
    job_type: "Forward Security Director",
    job_desc: "Bauch, Schuppe and Schulist Co",
    about_detail: "Hotels & Tourism",
    type: "full time",
    salary: "$40000-$42000",
    area: "New-York, USA",
  },
   {
    id:6,
    time: "12 min ago",
    img: job_logo_2,
    job_type: "Regional Creative Facilitator",
    job_desc: "Wisozk - Becker Co",
    about_detail: "Media",
    type: "full time",
    salary: "$$28000-$32000",
    area: "Los- Angeles, USA",
  },
   {
    id:5,
    time: "10 min ago",
    img: job_logo,
    job_type: "Forward Security Director",
    job_desc: "Bauch, Schuppe and Schulist Co",
    about_detail: "Hotels & Tourism",
    type: "full time",
    salary: "$40000-$42000",
    area: "New-York, USA",
  },
   {
    id:6,
    time: "12 min ago",
    img: job_logo_2,
    job_type: "Regional Creative Facilitator",
    job_desc: "Wisozk - Becker Co",
    about_detail: "Media",
    type: "full time",
    salary: "$$28000-$32000",
    area: "Los- Angeles, USA",
  }, {
    id:7,
    time: "10 min ago",
    img: job_logo,
    job_type: "Forward Security Director",
    job_desc: "Bauch, Schuppe and Schulist Co",
    about_detail: "Hotels & Tourism",
    type: "full time",
    salary: "$40000-$42000",
    area: "New-York, USA",
  },
   {
    id:8,
    time: "12 min ago",
    img: job_logo_2,
    job_type: "Regional Creative Facilitator",
    job_desc: "Wisozk - Becker Co",
    about_detail: "Media",
    type: "full time",
    salary: "$$28000-$32000",
    area: "Los- Angeles, USA",
  },
];

export default MyData;
